server:
  port: 8080

spring:
  application:
    name: pg-dev-guide-api
  datasource:
    driver-class-name: org.postgresql.Driver
    # [Original Schema: aitf] -> [Target Schema: pgdev]
    url: jdbc:postgresql://ep-bitter-sun-a44cor85.us-east-1.aws.neon.tech:5432/verceldb?currentSchema=pgdev&sslmode=require
    username: default
    password: 1zGNCST4qeBh
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.pg.api
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null

security:
  jwt:
    secret: CJPG_SUPER_SECRET_TOKEN_KEY_2026_1234567890
    issuer: pg-dev-guide
    expiration-seconds: 3600
